[package]
name = "compute-state-memory"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "In-process Compute control state"

[dependencies]
async-trait.workspace = true
compute-state = { path = "../compute-state" }
tokio.workspace = true

[dev-dependencies]
tokio.workspace = true
