[package]
name = "compute-runtime-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
compute-core = { path = "../compute-core" }
async-trait.workspace = true
tokio.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
serde_json.workspace = true

[dev-dependencies]
compute-runtime-conformance = { path = "../compute-runtime-conformance" }
tempfile.workspace = true
tokio.workspace = true
wat.workspace = true
