[package]
name = "compute-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "compute"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
compute-core = { path = "../compute-core" }
compute-environment = { path = "../compute-environment" }
compute-state = { path = "../compute-state" }
compute-state-file = { path = "../compute-state-file" }
compute-state-memory = { path = "../compute-state-memory" }
compute-state-feltdb = { path = "../compute-state-feltdb" }
compute-placement = { path = "../compute-placement" }
compute-policy = { path = "../compute-policy" }
compute-provider = { path = "../compute-provider" }
compute-runtime = { path = "../compute-runtime" }
chrono.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tempfile.workspace = true
tar.workspace = true
toml.workspace = true
walkdir.workspace = true

[dev-dependencies]
libc.workspace = true
assert_cmd = "2.0"
predicates = "3.1"
tempfile.workspace = true
wat.workspace = true
