[package]
name = "compute-provider"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
chrono.workspace = true
compute-core = { path = "../compute-core" }
compute-runtime = { path = "../compute-runtime" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
tokio.workspace = true

[dev-dependencies]
wat.workspace = true
